-- 1. Total Revenue
-- Calculates total revenue generated across all orders

SELECT SUM(sales) AS total_revenue
FROM sales;


-- 2. Total Profit
-- Calculates total profit generated

SELECT SUM(profit) AS total_profit
FROM sales;


-- 3. Total Number of Customers
-- Counts unique customers in the dataset

SELECT COUNT(DISTINCT customer_id) AS total_customers
FROM sales;


-- 4. Top 10 Customers by Revenue
-- Identifies the highest revenue generating customers

SELECT customer_name,
       SUM(sales) AS lifetime_revenue
FROM sales
GROUP BY customer_name
ORDER BY lifetime_revenue DESC
LIMIT 10;


-- 5. Customer Purchase Frequency
-- Shows which customers place the most orders

SELECT customer_name,
       COUNT(DISTINCT order_id) AS total_orders
FROM sales
GROUP BY customer_name
ORDER BY total_orders DESC
LIMIT 10;


-- 6. Customer Lifetime Value (CLV)
-- Calculates total revenue and profit generated by each customer

SELECT
    customer_id,
    customer_name,
    COUNT(DISTINCT order_id) AS total_orders,
    SUM(sales) AS lifetime_revenue,
    SUM(profit) AS lifetime_profit,
    ROUND(SUM(sales) / COUNT(DISTINCT order_id), 2) AS avg_order_value
FROM sales
GROUP BY customer_id, customer_name
ORDER BY lifetime_revenue DESC;


-- 7. Revenue by Customer Segment
-- Identifies which segment generates the most revenue

SELECT segment,
       SUM(sales) AS total_revenue
FROM sales
GROUP BY segment
ORDER BY total_revenue DESC;


-- 8. Revenue by Region
-- Compares geographic performance

SELECT region,
       SUM(sales) AS revenue
FROM sales
GROUP BY region
ORDER BY revenue DESC;


-- 9. Product Category Performance
-- Shows revenue and profit by product category

SELECT category,
       SUM(sales) AS revenue,
       SUM(profit) AS profit
FROM sales
GROUP BY category
ORDER BY profit DESC;


-- 10. Top 10 Products by Revenue
-- Identifies best-selling products

SELECT product_name,
       SUM(sales) AS total_revenue
FROM sales
GROUP BY product_name
ORDER BY total_revenue DESC
LIMIT 10;


-- 11. Monthly Sales Trend
-- Tracks revenue over time

SELECT DATE_TRUNC('month', order_date) AS month,
       SUM(sales) AS monthly_revenue
FROM sales
GROUP BY month
ORDER BY month;


-- 12. Discount Impact on Profitability
-- Evaluates how discounts affect average profit

SELECT discount,
       AVG(profit) AS avg_profit
FROM sales
GROUP BY discount
ORDER BY discount;


-- 13. Customer Revenue Ranking
-- Uses a window function to rank customers by lifetime revenue

SELECT
    customer_id,
    customer_name,
    SUM(sales) AS lifetime_revenue,
    RANK() OVER (ORDER BY SUM(sales) DESC) AS revenue_rank
FROM sales
GROUP BY customer_id, customer_name;

